# bash aliases


# bash commands - directory navigation
alias l='ls -CF'
alias ll='ls -l'
alias lla='ls -l -a'
alias lls='ls -l -s'
alias c.='cd ..'


# [git]
alias gd="git diff"
alias gs="git status"
alias ga="git add"
alias gaa="git add ."
alias gb="git branch"
alias gc="git commit"


# [vim]
alias v="vim"


# [docker]
alias d="docker"
alias dps="docker ps"


# [kubernetes]


# [terraform]
alias tf="terraform"
alias tfa="terraform apply"


