# bash aliases


# bash commands - directory navigation
alias l='ls -CF'
alias ll='ls -l'
alias la='ls -la'
alias lla='ls -l -a'
alias lls='ls -l -s'
alias c.='cd ..'



# matlab
alias matlab='~/.matlab/bin/matlab -nojvm -nosplash'

# gnu octave
alias octave='octave --no-gui'
